from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from LatentDenoisingAAE import LatentDenoisingAAE
import matplotlib.pyplot as plt
import torchvision.utils as vutils

if __name__ == '__main__':
    batch_size = 128
    transform = transforms.Compose([
        transforms.ToTensor()
    ])
    mnist_train = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
    mnist_loader = DataLoader(mnist_train, batch_size=batch_size, shuffle=True)
    mnist_test = datasets.MNIST(root="./data", train=False, download=True, transform=transforms.ToTensor())
    test_loader = DataLoader(mnist_test, batch_size=1000, shuffle=False)
    latent_dim = 256
    encoder_layers = [784, 512]
    decoder_layers = [512, 784]
    discriminator_layers = [256]
    diffusion_layers = [256, 256]
    num_epochs = 20
    ld_aae = LatentDenoisingAAE(latent_dim=latent_dim, encoder_layers=encoder_layers,
                                    decoder_layers=decoder_layers, discriminator_layers=discriminator_layers,
                                    diffusion_layers=diffusion_layers)
    
    ld_aae.train(mnist_loader, num_epochs=num_epochs)

    generated_samples = ld_aae.generate_samples(1000)
    grid = vutils.make_grid(generated_samples[:16].cpu().float(), nrow=4, normalize=True)
    plt.figure(figsize=(6,6))
    plt.imshow(grid.permute(1, 2, 0).numpy())
    plt.title(f"Samples generated by Latent Denoising AAE")
    plt.axis("off")
    plt.show()

    fid_score = ld_aae.get_fid_score(test_loader=test_loader, fid_batch_size=100)
    print("FID Score:", fid_score)
